---
name:   Farmville                  # The application display name
short:  Farmville                       # A shortened name for reference
appid:  edu.cornell.cs5416.farmville     # Application identifier for Mac, iOS, Android

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h
modules:
    - graphics
    - scene2
# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - cmake                     # This supports all Desktop platforms
